name: Build and Package Electron App

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build app (if needed)
        run: npm run build
        continue-on-error: true

      - name: Package Electron app
        run: npx electron-packager . my-app --platform=win32 --arch=x64 --out=dist --overwrite

      - name: Copy Electron runtime files
        run: |
          $electronDist = "node_modules/electron/dist"
          $appDist = Get-ChildItem -Path dist -Directory | Select-Object -First 1
          Copy-Item "$electronDist\ffmpeg.dll" "$appDist\"
          Copy-Item "$electronDist\icudtl.dat" "$appDist\"
          Copy-Item "$electronDist\snapshot_blob.bin" "$appDist\"
          Copy-Item "$electronDist\d3dcompiler_47.dll" "$appDist\"
          Copy-Item "$electronDist\libEGL.dll" "$appDist\"
          Copy-Item "$electronDist\libGLESv2.dll" "$appDist\"
        shell: pwsh

      - name: Zip package
        run: |
          $appDist = Get-ChildItem -Path dist -Directory | Select-Object -First 1
          Compress-Archive -Path "$appDist\*" -DestinationPath "my-app-win.zip"
        shell: pwsh

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-app-win
          path: my-app-win.zip
